substitutions:
  name: radio-tx
  device_description: FM Radio Transmitter using Si4713
  friendly_name: FM Radio Transmitter

external_components:
  - source: ../components
    components: [si4713]
    # - source: github://jhollowe/esphome_components
    #   components: [si4713]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: "ps8x3urIdHKJ83Ls2JlIHkLdITJnWqSiOfLnTqBWD74="

ota:
  - platform: esphome
    password: "91f3a25017022969968c7c7b2fe7721e"

wifi:
  ssid: !secret fake_wifi_ssid
  password: !secret fake_wifi_password

  ap:

mdns:
  disabled: false

captive_portal:

web_server:
  port: 80
  version: 3

i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true
  id: fm_tx_bus

si4713:
  reset_pin: GPIO20
  id: tx_id

button:
  - platform: si4713
    reset:
      name: "${friendly_name} Reset"
      id: tx_reset


number:
  - platform: si4713
    frequency:
      name: "${friendly_name} Frequency"
      id: tx_frequency
    power_level:
      name: "${friendly_name} Power"
      id: tx_power


switch:
  - platform: si4713
    enable_tx:
      name: "${friendly_name} Enable Transmit"
      id: tx_enable
      restore_mode: RESTORE_DEFAULT_ON
